server:
  port: 5000

spring.security.user.name: admin
spring.security.user.password: admin
spring.security.user.roles: admin

jwt:
  secret: 984hg493gh0439rthr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 30m

spring:
  application:
    name: CourseManagementSystem

  datasource:
    driver-class-name: org.h2.Driver
    username: ""
    password: ""
    url: "jdbc:h2:./database"

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yml

  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true

  main:
    allow-circular-references: true